name: Release

on:
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: 🔢 Get version
              id: app_version
              run: echo "result=$(./version.sh)" >> $GITHUB_OUTPUT

            - name: 🔎 Check for tag
              id: tag_exists
              run: echo "result=$(./tag-exists.sh)" >> $GITHUB_OUTPUT
              env:
                  TAG_NAME: v${{ steps.app_version.outputs.result }}

            - name: 🔨 Build executables
              run: ./scripts/build.sh
              if: ${{ steps.tag_exists.outputs.result }} != "yes"

            - name: 🚀 Upload executables
              uses: ncipollo/release-action@v1
              with:
                  tag: v${{ steps.app_version.outputs.result }}
                  artifacts: "*.AppImage"
                  generateReleaseNotes: false
                  draft: false
                  artifactErrorsFailBuild: true
